/*
 * Captures real probe results to a fixture file so preview.html can render
 * the actual panel offline, through the real content.js code path.
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const core = require('../src/lib/core.js');
const here = dirname(fileURLToPath(import.meta.url));

const IDS = ['X1gxkuNzMf4', 'AAAAAAAAAAA'];
const out = {};

for (const id of IDS) {
  process.stdout.write(`probing ${id} ... `);
  const r = await core.recover(id);
  r.verdict = core.verdictFor(id === 'AAAAAAAAAAA' ? core.STATE.GONE : core.STATE.PRIVATE, r);
  r.links = core.externalLinks(id);
  out[id] = r;
  console.log(r.found ? `found: ${r.title}` : 'no record');
}

writeFileSync(
  join(here, 'preview-data.js'),
  '/* generated by make-preview.mjs — do not edit */\n' +
  'window.__YTRP_FIXTURES = ' + JSON.stringify(out, null, 2) + ';\n',
  'utf8'
);
console.log('wrote test/preview-data.js');
